import 'package:youtube_explode_dart/youtube_explode_dart.dart';
import 'package:http/http.dart' as http;

void main() async {
  var yt = YoutubeExplode();
  var videoIds = ['PnJPBiVvVX4', '7rVeDSHb6lw'];

  for (var id in videoIds) {
    print('Analyzing video: $id');
    try {
      var manifest = await yt.videos.closedCaptions.getManifest(id);
      print('Tracks found: ${manifest.tracks.length}');
      
      for (var track in manifest.tracks) {
        print(' - Track: [${track.language.code}] IsAuto: ${track.isAutoGenerated}');
        
        // Try different formats by appending &fmt=
        var formats = ['srv1', 'srv2', 'srv3', 'vtt', 'ttml'];
        for (var fmt in formats) {
           var url = track.url.toString();
           // Replace or append fmt
           if (url.contains('fmt=')) {
              url = url.replaceAll(RegExp(r'fmt=[^&]+'), 'fmt=$fmt');
           } else {
              url += '&fmt=$fmt';
           }
           
           try {
              var response = await http.get(Uri.parse(url), headers: {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
                'Accept': '*/*',
                'Accept-Language': 'en-US,en;q=0.9',
                'Referer': 'https://www.youtube.com/watch?v=$id',
                'Origin': 'https://www.youtube.com',
              });
              if (response.statusCode == 200 && response.body.isNotEmpty) {
                 print('   -> FORMAT $fmt: SUCCESS! length: ${response.body.length}');
              } else {
                 print('   -> FORMAT $fmt: FAILED (Status: ${response.statusCode}, Length: ${response.body.length})');
              }
           } catch (e) {
              print('   -> FORMAT $fmt: ERROR: $e');
           }
        }
      }
    } catch (e) {
      print('Error getting manifest: $e');
    }
    print('---');
  }
  yt.close();
}
